language: python
python:
  - 2.7
  - 3.4
env:
  global:
    - DATABASE_URL=postgis://postgres:@localhost/travis_ci_test
    - DEFAULT_FROM_EMAIL=test@domain.net
    - EMAIL_HOST=localhost
    - EMAIL_PORT=25
    - FACEBOOK_APP_KEY=fb_key
    - FACEBOOK_APP_SECRET=fb_secret
    - SECRET_KEY=test
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
before_script:
  - psql -U postgres -c 'create database travis_ci_test'
  - psql -U postgres -c 'create extension postgis' -d travis_ci_test
  - psql -U postgres -c 'create extension postgis_topology' -d travis_ci_test
  - python manage.py migrate
script:
  - python manage.py test
addons:
  postgresql: "9.3"
services:
  - postgresql
